### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by younes0**

### CODE REVIEW

**Comment by bartoszkubicki** [comment]
Thank you for your effort! Plese see my comment in code. Have yout tested extension on php 7.2?

**Comment by younes0** [comment]
Yes i've tested the module in PHP 7.2 and magento 2.3.3 (uploading via admin and getting attached file via repository)

**Comment by younes0** [comment]
Is it good for you @bartoszkubicki or do I need to make changes ? thanks.

**Comment by bartoszkubicki** [comment]
@younes0 if it is not a problem modify your commit. If you can't do it please let me know and I will do it as separate PR.

**Comment by younes0** [comment]
@bartoszkubicki what would you want me to change ? :)

**Comment by younes0** [comment]
@bartoszkubicki commit is now better I think: supporting php 7.1.X && php 7.2.X

**Comment by bartoszkubicki** [comment]
@younes0 thank you very much for your contribution.

**Comment by younes0** [comment]
Thank you!

**Pull request merged**
